# Database configuration
spring:
  datasource:
    url: jdbc:<your-database-driver>://<your-database-host>:<your-database-port>/<your-database-name>?useUnicode=true&characterEncoding=utf-8
    username: <your-database-username>
    password: <your-database-password>

# Initial admin configuration (an admin will be inserted into the database when the application starts)
  security:
    user:
      name: <your-admin-username>
      email: <your-admin-email>
      password: <your-admin-password>
